apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: IMAGE
      type: string
      description: Reference of the image buildah will produce
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/ci-cd-app:latest
  workspaces:
    - name: output

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: https://github.com/shubhranshu-pandey/ci-cd-final-project
      workspaces:
        - name: output
          workspace: output

    - name: flake8
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - flake8
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: FORMAT
          value: docker
      runAfter:
        - nose
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - buildah
      workspaces:
        - name: source
          workspace: output
