---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-world-pipeline
spec:
  params:
    - name: message
  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: message
          value: "$(params.message)"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch
      default: "main"
  tasks:
    - name: clone
      taskRef:
        name: checkout
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    # Task of project: Add placeholder Tasks with reference to echo Task
    - name: lint
      runAfter:
        - clone
      taskRef:
        name: echo
      params:
        - name: message
          value: "Calling Flake8 linter..."
    
    - name: tests
      runAfter:
        - lint
      taskRef:
        name: echo
      params:
        - name: message
          value: "Running unit tests with PyUnit"
    
    - name: build
      runAfter:
        - tests
      taskRef:
        name: echo
      params:
        - name: message
          value: "Building image for $(params.repo-url)..."
    
    - name: deploy
      runAfter:
        - build
      taskRef:
        name: echo
      params:
        - name: message
          value: "Deploying $(params.branch) branch of $(params.repo-url)..."
...
