---
name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    # It's important to consistently use same version of 
    # dependencies and operating system for all phases of development 
    # including CI pipeline --> Project developed on Python 3.9!
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        # --upgrade: Update pip to latest version if already installed.
        # Always good practice to make sure latest version of pip
        # is installed to minimize installation problems.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Make sure that everyone who contributes is following same style guidelines
      # NOTE: Course requirement -> Only service folder is linted 
      #   and only certain functions of flake8 are used.
      - name: Lint service folder with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
...